name: Run lint on a pull request

on:
  pull_request:
    branches:    
      - master
    paths:
      - ofmt/**
      - eslint-config-ofmt/**

jobs:
  lint:
    name: Lint the code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18]
    steps:
    - uses: ottofeller/github-actions/npm-run@main
      with:
        node-version: ${{ matrix.version }}
        command: npm run lint
        directory: ./eslint-config-ofmt
    - uses: ottofeller/github-actions/npm-run@main
      with:
        node-version: ${{ matrix.version }}
        command: cd ../eslint-config-ofmt && npm ci && cd ../ofmt && npm run lint
        directory: ./ofmt
