name: Run lint on a pull request

on:
  pull_request:
    branches:    
      - master
    paths:
      - ofmt/**

jobs:
  lint:
    name: Lint the code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [12, 16]
    steps:
    - uses: ottofeller/github-actions/npm-run@main
      with:
        node-version: ${{ matrix.version }}
        command: npm run lint
        directory: ./ofmt
