name: Bump version tag
on: workflow_dispatch

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: bump-version
      name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 0.11.4
        PRERELEASE_SUFFIX: ""
        RELEASE_BRANCHES: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        tag_name: ${{ steps.bump-version.outputs.new_tag }}
        name: ${{ steps.bump-version.outputs.new_tag }}
