name: Bump version and create release

on:
  workflow_dispatch:
    inputs:
      bump-level:
        description: Version level to be bumped
        default: patch
        required: false
        type: choice
        options:
        - none
        - patch
        - minor
        - major

jobs:
  create:
    name: Bump version and create release
    runs-on: ubuntu-latest
    steps:
    - uses: ottofeller/github-actions/create-release@main
      with:
        initial-version: 1.0.3
        bump-level: ${{ github.event.inputs.bump-level }}
        release-branches: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        update-children-path: |
          eslint-config-ofmt
          prettier-config-ofmt
          ofmt
        update-children-bump-level: |
          ${{ github.event.inputs.bump-level }}
          ${{ github.event.inputs.bump-level }}
          ${{ github.event.inputs.bump-level }}
